# Dockerfile.transformation
FROM python:3.8

# Install any necessary dependencies
RUN pip install requests

# Copy the data transformation script into the container
COPY data_transformation_script.py /app/data_transformation_script.py

# Set the working directory
WORKDIR /app

# Command to run the data ingestion script
CMD ["python", "data_transformation_script.py"]
